linters:
  NestingDepth:
    enabled: false
  SelectorDepth:
    enabled: false
  QualifyingElement:
    allow_element_with_attribute: true
  SpaceBeforeBrace:
    allow_single_line_padding: true
  PropertySortOrder:
    order:
      # ----- Special -----
      - content
      - font-size # other dimentions can be set in "em" relative to the font-size
      # ----- Positioning -----
      - position
      - z-index
      - top
      - right
      - bottom
      - left
      - float
      # ----- Display & Box Model -----
      - display
      - overflow
      - overflow-wrap
      - overflow-x
      - overflow-y
      - box-shadow
      - box-sizing
      # ----- Dimensions -----
      - width
      - min-width
      - max-width
      - height
      - min-height
      - max-height
      - line-height
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      - border
      - border-top
      - border-color
      - border-top-color
      - border-top-left-radius
      - border-top-right-radius
      - border-style
      - border-top-style
      - border-width
      - border-top-width
      - border-right
      - border-right-color
      - border-right-style
      - border-right-width
      - border-bottom
      - border-bottom-color
      - border-bottom-left-radius
      - border-bottom-right-radius
      - border-bottom-style
      - border-bottom-width
      - border-left
      - border-left-color
      - border-left-style
      - border-left-width
      - border-radius
      - border-collapse
      - border-image-outset
      - border-image-repeat
      - border-image-slice
      - border-image-source
      - border-image-width
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      # ----- Background & Color -----
      - background
      - background-attachment
      - background-blend-mode
      - background-clip
      - background-color
      - background-image
      - background-origin
      - background-position
      - background-repeat
      - background-size
      - color
      - color-interpolation
      - color-interpolation-filters
      - color-rendering
      # ----- Type -----
      - font-family
      - font-kerning
      - font-stretch
      - font-style
      - font-variant
      - font-variant-ligatures
      - font-weight
      - text-align
      - text-anchor
      - text-decoration
      - text-indent
      - text-rendering
      - text-shadow
      - text-overflow
      - text-transform
      - letter-spacing
      # ----- Other -----
      - caption-side
      - clear
      - clip
      - cursor
      - direction
      - empty-cells
      - image-rendering
      - list-style-image
      - list-style-position
      - list-style-type
      - object-fit
      - object-position
      - opacity
      - orphans
      - outline-color
      - outline-offset
      - outline-style
      - outline-width
      - page-break-after
      - page-break-before
      - page-break-inside
      - pointer-events
      - resize
      - speak
      - table-layout
      - tab-size
      - touch-action
      - transition-delay
      - transition-duration
      - transition-property
      - transition-timing-function
      - unicode-bidi
      - vertical-align
      - visibility
      - white-space
      - widows
      - will-change
      - word-break
      - word-spacing
      - word-wrap
      - backface-visibility
      - align-content
      - align-items
      - align-self
      - flex-basis
      - flex-grow
      - flex-shrink
      - flex-direction
      - flex-wrap
      - justify-content
      - order
      - perspective
      - perspective-origin
      - shape-outside
      - shape-image-threshold
      - shape-margin
      - transform
      - transform-origin
      - transform-style
      - buffered-rendering
      - clip-path
      - clip-rule
      - mask
      - filter
      - flood-color
      - flood-opacity
      - lighting-color
      - stop-color
      - stop-opacity
      - fill
      - fill-opacity
      - fill-rule
      - marker-end
      - marker-mid
      - marker-start
      - mask-type
      - shape-rendering
      - stroke
      - stroke-dasharray
      - stroke-dashoffset
      - stroke-linecap
      - stroke-linejoin
      - stroke-miterlimit
      - stroke-opacity
      - stroke-width
      - alignment-baseline
      - baseline-shift
      - dominant-baseline
      - writing-mode
      - glyph-orientation-horizontal
      - glyph-orientation-vertical
      - vector-effect
      - paint-order
      - zoom