language: go

go:
  - 1.7
  - tip

matrix:
  allow_failures:
  - go: tip
  fast_finish: true

os:
  - linux
  - osx

env:
  global:
    - APM_TEST_PACKAGES="environment go-config go-get autocomplete-go gofmt navigator-go tester-go gorename gometalinter-linter linter builder-go go-debug godoc"
    - ATOM_LINT_WITH_BUNDLED_NODE="false"
    - NVM_DIR="$HOME/.nvm"
  matrix:
    - ATOM_CHANNEL=beta
    - ATOM_CHANNEL=stable

notifications:
  email:
    on_success: never
    on_failure: change

install:
  - rm -rf "$NVM_DIR"
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh | bash
  - source "$NVM_DIR/nvm.sh"
  - nvm install node
  - nvm use node

script:
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u sourcegraph.com/sqs/goreturns
  - go get -u github.com/rogpeppe/godef
  - go get -u github.com/nsf/gocode
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install --update
  - 'curl -s https://raw.githubusercontent.com/atom/ci/943a16cd32926bdfcca703f16ec6a958a2db38a5/build-package.sh | sh'

sudo: false

git:
  depth: 10

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

branches:
  only:
    - master
