notifications:
  email:
    on_success: never
    on_failure: change

sudo: false

os:
  - linux
  - osx

language: go

go:
  - 1.6.2

env:
  global:
    - APM_TEST_PACKAGES="environment"

  matrix:
    - ATOM_CHANNEL=beta
    - ATOM_CHANNEL=stable

script:
  - 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'


addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

git:
  depth: 10

branches:
  only:
    - master
