if not vim.g.vscode then
	require("mike.options")
	require("mike.keymaps")
	require("mike.plugins")
	require("mike.treesitter")
	require("mike.colorscheme")
	require("mike.nvim-cmp")
	require("mike.mason")
	require("mike.lsp")
	require("mike.telescope")
	require("mike.lua_line")
	require("mike.indent_blankline")
	require("mike.emmet")
	require("mike.nvim-tree")
	require("mike.trouble")
	require("mike.vim-test")
	require("mike.languages")
	require("mike.toggle-term")
	require("mike.hop")
	require("mike.luasnip")
  -- require("mike.elixir")
end
