-- vim.api.nvim_set_keymap("n", "<C-P>", ":Files<cr>", { noremap = true, silent = true })
-- vim.api.nvim_set_keymap("n", "<C-B>", ":Buffers<cr>", { noremap = true, silent = true })
-- vim.api.nvim_set_keymap("n", "<C-T>", ":Rg<cr>", { noremap = true, silent = true })
