require("nvim-treesitter.configs").setup({
  ensure_installed = {
    "astro",
    "bash",
    "comment",
    "cmake",
    "css",
    "dockerfile",
    "eex",
    "elixir",
    "erlang",
    "gleam",
    "go",
    "gomod",
    "graphql",
    "hcl",
    "heex",
    "help",
    "hjson",
    "html",
    "http",
    "javascript",
    "jsdoc",
    "json",
    "json5",
    "jsonc",
    "lua",
    "make",
    "markdown",
    "python",
    "regex",
    "ruby",
    "rust",
    "scss",
    "surface",
    "svelte",
    "todotxt",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "vue",
    "yaml",
  },
  ignore_install = { "haskell", "phpdoc" },
  context_commentstring = { enable = true },
  highlight = { enable = true },
  rainbow = { enable = true },
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = "<leader>is",
      scope_incremental = "<leader>is",
      node_incremental = "<TAB>",
      node_decremental = "<S-TAB>",
    },
  },
  autotag = {
    enable = true,
    filetypes = {
      'html', 'javascript', 'typescript', 'javascriptreact', 'typescriptreact', 'svelte', 'vue', 'tsx', 'jsx', 'rescript',
      'xml', 'php', 'markdown', 'glimmer', 'handlebars', 'hbs', 'heex', 'html-eex', 'phoenix-heex'
    }
  },
})
